#!/bin/sh

git config --global user.email "yourmom@pivotal.io"
git config --global user.name "Your Mom"


cd `dirname $0`
git pull
date > file.txt
git add file.txt
git commit -m "Updated file.txt."
git checkout test
git merge master

